<?php

declare(strict_types=1);

$pageTitle = 'Fuel Sales Report | FuelOps Admin Dashboard';
$pageHeading = 'Fuel Sales Report';
$currentRoute = 'admin/fuel-sales-report';
require __DIR__ . '/fuel-sales-page-setup.php';
require __DIR__ . '/../includes/header.php';
?>
<main class="clock-in-page fuel-module-page" data-fuel-chart-data="<?php echo e(json_encode($fuelChartData, JSON_HEX_APOS | JSON_HEX_QUOT)); ?>">
    <section class="clock-hero fuel-hero"><div class="container-fluid"><nav class="fuel-breadcrumb"><a href="<?php echo e(route_url('admin/dashboard')); ?>">Dashboard</a><i class="fa-solid fa-chevron-right"></i><span>Fuel Sales</span><i class="fa-solid fa-chevron-right"></i><span>Reports</span></nav><div class="clock-hero__content fuel-hero-card"><div><span class="eyebrow">Sales Analytics</span><h1>Fuel Sales Report</h1><p>Review revenue, litres sold, pump performance, variance, and fuel type sales from verified database records.</p></div><div class="dropdown"><button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown"><i class="fa-solid fa-download"></i>Export</button><ul class="dropdown-menu dropdown-menu-end"><li><button class="dropdown-item" data-fuel-export="PDF" type="button">PDF</button></li><li><button class="dropdown-item" data-fuel-export="Excel" type="button">Excel</button></li><li><button class="dropdown-item" data-fuel-export="CSV" type="button">CSV</button></li></ul></div></div></div></section>
    <section class="container-fluid clock-workspace"><div class="fuel-summary-grid"><?php foreach ($fuelReportKpis as $card): ?><article class="fuel-summary-card fuel-summary-card--<?php echo e($card['tone']); ?>"><span><i class="<?php echo e($card['icon']); ?>"></i></span><div><small><?php echo e($card['label']); ?></small><strong><?php echo e($card['value']); ?></strong></div></article><?php endforeach; ?></div><article class="app-card card fuel-table-card mt-4"><div class="fuel-toolbar"><div><span class="eyebrow">Report Records</span><h2>Sales & Variance Report</h2></div></div><div class="table-responsive"><table class="table attendance-table fuel-table align-middle"><thead><tr><th>Date</th><th>Transaction</th><th>Employee</th><th>Pump</th><th>Fuel Type</th><th>Litres</th><th>Expected</th><th>Collected</th><th>Variance</th><th>Status</th></tr></thead><tbody><?php foreach ($fuelSales as $sale): ?><tr><td><?php echo e(format_date($sale['date'])); ?></td><td><strong><?php echo e($sale['transaction_id']); ?></strong></td><td><?php echo e($sale['attendant']); ?></td><td><?php echo e($sale['pump']); ?></td><td><?php echo e($sale['fuel_type']); ?></td><td><?php echo e(number_format($sale['liters_sold'], 2)); ?> L</td><td>NGN <?php echo e(number_format($sale['expected_amount'], 2)); ?></td><td>NGN <?php echo e(number_format($sale['amount_collected'], 2)); ?></td><td>NGN <?php echo e(number_format($sale['variance'], 2)); ?></td><td><span class="table-badge <?php echo e($salesStatusClasses[$sale['status']] ?? 'fuel-status--pending'); ?>"><?php echo e($sale['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></article></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>
