<?php

declare(strict_types=1);

$pageTitle = 'Leave Types | FuelOps Admin Dashboard';
$pageHeading = 'Leave Types';
$currentRoute = 'admin/leave-types';
require __DIR__ . '/leave-management-setup.php';
require __DIR__ . '/../includes/header.php';
?>
<main class="clock-in-page leave-module-page">
    <section class="clock-hero leave-hero"><div class="container-fluid"><nav class="leave-breadcrumb"><a href="<?php echo e(route_url('admin/dashboard')); ?>">Dashboard</a><i class="fa-solid fa-chevron-right"></i><span>Leave Management</span><i class="fa-solid fa-chevron-right"></i><span>Leave Types</span></nav><div class="clock-hero__content leave-hero-card"><div><span class="eyebrow">Policy Categories</span><h1>Leave Types</h1><p>Create and manage leave categories, maximum days, payment status, and availability.</p></div><span class="leave-hero-icon"><i class="fa-solid fa-list-check"></i></span></div></div></section>
    <section class="container-fluid clock-workspace">
        <div class="leave-summary-grid leave-summary-grid--three"><?php foreach ($typeStats as $card): ?><article class="leave-summary-card leave-summary-card--<?php echo e($card['tone']); ?>"><span><i class="<?php echo e($card['icon']); ?>"></i></span><div><small><?php echo e($card['label']); ?></small><strong><?php echo e($card['value']); ?></strong></div></article><?php endforeach; ?></div>
        <div class="row g-4 mt-1"><div class="col-xl-7"><article class="app-card card leave-table-card h-100"><div class="leave-toolbar"><div><span class="eyebrow">Leave Categories</span><h2>Configured Leave Types</h2></div></div><div class="table-responsive"><table class="table attendance-table leave-table align-middle"><thead><tr><th>Leave Type</th><th>Description</th><th>Maximum Days</th><th>Paid / Unpaid</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($leaveTypes as $type): ?><tr><td><strong><?php echo e($type['name']); ?></strong></td><td><?php echo e($type['description']); ?></td><td><?php echo e((string) $type['max_days']); ?></td><td><?php echo $type['paid'] ? 'Paid' : 'Unpaid'; ?></td><td><span class="table-badge <?php echo e($leaveStatusClasses[$type['status']]); ?>"><?php echo e($type['status']); ?></span></td><td><div class="leave-actions"><button class="btn btn-sm btn-light" data-leave-type-edit="<?php echo e($type['name']); ?>" type="button" title="Edit"><i class="fa-solid fa-pen-to-square"></i></button><button class="btn btn-sm btn-light leave-action-danger" data-leave-type-delete="<?php echo e($type['name']); ?>" type="button" title="Delete"><i class="fa-solid fa-trash"></i></button></div></td></tr><?php endforeach; ?></tbody></table></div></article></div><div class="col-xl-5"><form class="app-card card leave-form-card needs-validation" id="leaveTypeForm" novalidate><div class="leave-section-heading"><span><i class="fa-solid fa-plus"></i></span><div><small>Add Leave Type</small><h2>New Leave Category</h2></div></div><label class="form-label" for="leaveName">Leave Name</label><input class="form-control" id="leaveName" placeholder="Enter leave name" required><label class="form-label" for="leaveDescription">Description</label><textarea class="form-control" id="leaveDescription" rows="3" placeholder="Enter description" required></textarea><label class="form-label" for="leaveMaxDays">Maximum Days</label><input class="form-control" id="leaveMaxDays" type="number" min="1" value="7" required><div class="form-check form-switch leave-switch"><input class="form-check-input" type="checkbox" role="switch" id="leavePaid" checked><label class="form-check-label" for="leavePaid">Paid Leave</label></div><label class="form-label" for="leaveStatus">Status</label><select class="form-select" id="leaveStatus" required><option>Active</option><option>Inactive</option></select><div class="leave-form-actions"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-check"></i>Save</button><button class="btn btn-outline-brand" type="reset"><i class="fa-solid fa-rotate-left"></i>Reset</button></div></form></div></div>
    </section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>