<?php

declare(strict_types=1);

$pageTitle = 'Leave Requests | FuelOps Admin Dashboard';
$pageHeading = 'Leave Requests';
$currentRoute = 'admin/leave-requests';
require __DIR__ . '/leave-management-setup.php';
require __DIR__ . '/../includes/header.php';
?>
<main class="clock-in-page leave-module-page">
    <section class="clock-hero leave-hero"><div class="container-fluid"><nav class="leave-breadcrumb"><a href="<?php echo e(route_url('admin/dashboard')); ?>">Dashboard</a><i class="fa-solid fa-chevron-right"></i><span>Leave Management</span><i class="fa-solid fa-chevron-right"></i><span>Leave Requests</span></nav><div class="clock-hero__content leave-hero-card"><div><span class="eyebrow">Approval Desk</span><h1>Leave Requests</h1><p>Review incoming leave requests and simulate approval decisions in demo mode.</p></div><span class="leave-hero-icon"><i class="fa-solid fa-envelope-open-text"></i></span></div></div></section>
    <section class="container-fluid clock-workspace">
        <article class="app-card card leave-table-card">
            <div class="leave-toolbar"><div><span class="eyebrow">Incoming Requests</span><h2>Pending and Forwarded Leave Requests</h2></div></div>
            <div class="leave-filter-grid leave-filter-grid--requests"><div class="filter-control filter-control--wide"><i class="fa-solid fa-magnifying-glass"></i><input id="leaveRequestSearch" type="search" placeholder="Search employee name or ID"></div><select class="form-select" id="leaveRequestTypeFilter"><option value="">All leave types</option><?php foreach ($leaveTypeNames as $type): ?><option value="<?php echo e($type); ?>"><?php echo e($type); ?></option><?php endforeach; ?></select><select class="form-select" id="leaveRequestDepartmentFilter"><option value="">All departments</option><?php foreach ($departments as $department): ?><option value="<?php echo e($department); ?>"><?php echo e($department); ?></option><?php endforeach; ?></select><select class="form-select" id="leaveRequestRoleFilter"><option value="">All roles</option><?php foreach ($roles as $role): ?><option value="<?php echo e($role); ?>"><?php echo e($role); ?></option><?php endforeach; ?></select><select class="form-select" id="leaveRequestStatusFilter"><option value="">All statuses</option><?php foreach ($leaveStatuses as $status): ?><option value="<?php echo e($status); ?>"><?php echo e($status); ?></option><?php endforeach; ?></select><input class="form-control" id="leaveRequestFromFilter" type="date"><input class="form-control" id="leaveRequestToFilter" type="date"></div>
            <div class="table-responsive"><table class="table attendance-table leave-table align-middle"><thead><tr><th>Employee</th><th>Department</th><th>Leave Type</th><th>Start Date</th><th>End Date</th><th>Duration</th><th>Date Applied</th><th>Current Approval Stage</th><th>Status</th><th>Actions</th></tr></thead><tbody id="leaveRequestBody"><?php foreach ($leaveRequests as $request): ?><tr data-leave-request-row data-search="<?php echo e(strtolower($request['employee'] . ' ' . $request['employee_id'])); ?>" data-type="<?php echo e($request['type']); ?>" data-department="<?php echo e($request['department']); ?>" data-role="<?php echo e($request['role']); ?>" data-status="<?php echo e($request['status']); ?>" data-start="<?php echo e($request['start']); ?>"><td><strong><?php echo e($request['employee']); ?></strong><small><?php echo e($request['employee_id']); ?></small></td><td><?php echo e($request['department']); ?></td><td><?php echo e($request['type']); ?></td><td><?php echo e(date('d M Y', strtotime($request['start']))); ?></td><td><?php echo e(date('d M Y', strtotime($request['end']))); ?></td><td><?php echo e((string) $request['days']); ?> days</td><td><?php echo e(date('d M Y', strtotime($request['applied']))); ?></td><td><?php echo e($request['stage']); ?></td><td><span class="table-badge <?php echo e($leaveStatusClasses[$request['status']]); ?>"><?php echo e($request['status']); ?></span></td><td><div class="leave-actions"><button class="btn btn-sm btn-light" data-leave-view="<?php echo e((string) $request['id']); ?>" type="button" title="View"><i class="fa-solid fa-eye"></i></button><button class="btn btn-sm btn-light" data-leave-action="approve" data-leave-name="<?php echo e($request['employee']); ?>" type="button" title="Approve"><i class="fa-solid fa-check"></i></button><button class="btn btn-sm btn-light leave-action-danger" data-leave-action="reject" data-leave-name="<?php echo e($request['employee']); ?>" type="button" title="Reject"><i class="fa-solid fa-xmark"></i></button><button class="btn btn-sm btn-light" data-leave-action="forward" data-leave-name="<?php echo e($request['employee']); ?>" type="button" title="Forward"><i class="fa-solid fa-share"></i></button></div></td></tr><?php endforeach; ?></tbody></table></div>
        </article>
    </section>
</main>
<div class="modal fade" id="leaveDetailsModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content leave-modal"><div class="modal-header"><h5 class="modal-title">Leave Details</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div id="leaveDetailsContent"></div><label class="form-label mt-3" for="approvalNotes">Approval Notes</label><textarea class="form-control" id="approvalNotes" rows="3" placeholder="Optional approval notes"></textarea></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal" type="button">Close</button><button class="btn btn-primary" data-leave-action="note" data-leave-name="selected request" type="button">Save Notes</button></div></div></div></div>
<script>window.leaveRequests = <?php echo json_encode($leaveRequests, JSON_THROW_ON_ERROR); ?>;</script>
<?php require __DIR__ . '/../includes/footer.php'; ?>