<?php

declare(strict_types=1);

$pageTitle = 'My Profile | FuelOps Admin Dashboard';
$pageHeading = 'My Profile';
$currentRoute = 'admin/profile';
require __DIR__ . '/profile-management-setup.php';
require __DIR__ . '/../includes/header.php';
?>
<main class="clock-in-page profile-module-page">
    <section class="clock-hero profile-hero"><div class="container-fluid"><nav class="profile-breadcrumb"><a href="<?php echo e(route_url('admin/dashboard')); ?>">Dashboard</a><i class="fa-solid fa-chevron-right"></i><span>Profile</span></nav><div class="clock-hero__content profile-hero-card"><div><span class="eyebrow">Administrator Account</span><h1>My Profile</h1><p>View account details, profile information, security status, and recent activity.</p></div><span class="profile-hero-icon"><i class="fa-solid fa-user-shield"></i></span></div></div></section>
    <section class="container-fluid clock-workspace">
        <article class="app-card card profile-header-card">
            <div class="profile-avatar-wrap"><img src="<?php echo e(asset_url($admin['avatar'])); ?>" alt="Administrator profile picture" class="profile-avatar-lg"></div>
            <div class="profile-header-main"><span class="table-badge profile-status--active"><?php echo e($admin['status']); ?></span><h2><?php echo e($admin['name']); ?></h2><p><?php echo e($admin['role']); ?> • <?php echo e($admin['department']); ?></p><div class="profile-meta-grid"><span><i class="fa-solid fa-id-card"></i><?php echo e($admin['id']); ?></span><span><i class="fa-solid fa-calendar-plus"></i>Joined <?php echo e(format_date($admin['joined'])); ?></span><span><i class="fa-solid fa-clock"></i><?php echo e($admin['last_login']); ?></span><span><i class="fa-solid fa-envelope"></i><?php echo e($admin['email']); ?></span><span><i class="fa-solid fa-phone"></i><?php echo e($admin['phone']); ?></span></div></div>
            <div class="profile-header-actions"><a class="btn btn-primary" href="<?php echo e(route_url('admin/edit-profile')); ?>"><i class="fa-solid fa-user-pen"></i>Edit Profile</a><a class="btn btn-outline-brand" href="<?php echo e(route_url('admin/change-password')); ?>"><i class="fa-solid fa-key"></i>Change Password</a></div>
        </article>
        <div class="profile-summary-grid mt-4"><?php foreach ($activitySummary as $card): ?><article class="profile-summary-card profile-summary-card--<?php echo e($card['tone']); ?>"><span><i class="<?php echo e($card['icon']); ?>"></i></span><div><small><?php echo e($card['label']); ?></small><strong><?php echo e($card['value']); ?></strong></div></article><?php endforeach; ?></div>
        <div class="row g-4 mt-1">
            <div class="col-xl-6"><article class="app-card card profile-info-card h-100"><div class="profile-section-heading"><span><i class="fa-solid fa-address-card"></i></span><div><small>Personal Information</small><h2>Administrator Details</h2></div></div><div class="profile-info-grid"><div><small>Full Name</small><strong><?php echo e($admin['name']); ?></strong></div><div><small>Gender</small><strong><?php echo e($admin['gender']); ?></strong></div><div><small>Date of Birth</small><strong><?php echo e(format_date($admin['dob'])); ?></strong></div><div><small>Phone Number</small><strong><?php echo e($admin['phone']); ?></strong></div><div><small>Email Address</small><strong><?php echo e($admin['email']); ?></strong></div><div><small>Residential Address</small><strong><?php echo e($admin['address']); ?></strong></div><div><small>Emergency Contact</small><strong><?php echo e($admin['emergency_contact_name']); ?> • <?php echo e($admin['emergency_contact_phone']); ?></strong></div><div><small>Department</small><strong><?php echo e($admin['department']); ?></strong></div><div><small>Role</small><strong><?php echo e($admin['role']); ?></strong></div><div><small>Employee ID</small><strong><?php echo e($admin['id']); ?></strong></div><div><small>Date Joined</small><strong><?php echo e(format_date($admin['joined'])); ?></strong></div><div><small>Employment Status</small><strong><?php echo e($admin['status']); ?></strong></div></div></article></div>
            <div class="col-xl-6"><article class="app-card card profile-info-card h-100"><div class="profile-section-heading"><span><i class="fa-solid fa-lock"></i></span><div><small>Account Information</small><h2>Security Overview</h2></div></div><div class="profile-info-grid"><div><small>Username</small><strong><?php echo e($admin['username']); ?></strong></div><div><small>User Role</small><strong><?php echo e($admin['role']); ?></strong></div><div><small>Account Status</small><strong><?php echo e($admin['account_status']); ?></strong></div><div><small>Last Password Change</small><strong><?php echo e($admin['last_password_change']); ?></strong></div><div><small>Two-Factor Authentication</small><strong><?php echo e($admin['two_factor']); ?></strong></div><div><small>Last Login Date & Time</small><strong><?php echo e($admin['last_login']); ?></strong></div></div><div class="profile-login-list mt-3"><?php foreach ($loginHistory as $login): ?><div><span><i class="fa-solid fa-circle-check"></i></span><div><strong><?php echo e($login['date']); ?></strong><small><?php echo e($login['browser']); ?> • <?php echo e($login['ip']); ?></small></div></div><?php endforeach; ?></div></article></div>
        </div>
    </section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>
