<?php

declare(strict_types=1);

use App\Controllers\AdminController;
use App\Controllers\AttendanceController;
use App\Controllers\AuthController;
use App\Controllers\SupervisorController;
use App\Core\Router;
use App\Middleware\RbacMiddleware;

return static function (Router $router): void {
    $router->middleware(new RbacMiddleware());
    $router->get(['login', 'auth/login'], [AuthController::class, 'login']);
    $router->post(['login', 'auth/login'], [AuthController::class, 'authenticate']);
    $router->get(['logout', 'auth/logout'], [AuthController::class, 'logout']);
    $router->post('admin/change-password', [AdminController::class, 'updatePassword']);
    $router->post('admin/edit-profile', [AdminController::class, 'updateProfile']);
    $router->get(['profile/change-password', 'change-password'], [AttendanceController::class, 'changePassword']);
    $router->post(['profile/change-password', 'change-password'], [AttendanceController::class, 'updatePassword']);
    $router->post('admin/employees/store', [AdminController::class, 'storeEmployee']);
    $router->post('admin/employees/update', [AdminController::class, 'updateEmployee']);
    $router->post('admin/employees/delete', [AdminController::class, 'deleteEmployee']);
    $router->post('admin/employees/toggle-account', [AdminController::class, 'toggleEmployeeAccount']);
    $router->post('admin/employees/reset-password', [AdminController::class, 'resetEmployeePassword']);
    $router->post('admin/employees/upload-document', [AdminController::class, 'uploadEmployeeDocument']);
    $router->post('admin/employees/delete-document', [AdminController::class, 'deleteEmployeeDocument']);
    $router->post('admin/departments/save', [AdminController::class, 'saveDepartment']);
    $router->post('admin/departments/deactivate', [AdminController::class, 'deactivateDepartment']);
    $router->post('admin/settings/fuel-pricing/save', [AdminController::class, 'saveFuelPrices']);
    $router->post('admin/settings/company/save', [AdminController::class, 'saveCompanyInformation']);
    $router->post('admin/settings/system/save', [AdminController::class, 'saveSystemSettings']);
    $router->post('admin/fuel-sales/verify', [AdminController::class, 'verifyFuelSale']);
    $router->post('admin/fuel-inventory/delivery', [AdminController::class, 'saveFuelDelivery']);
    $router->post('admin/announcements/store', [AdminController::class, 'storeAnnouncement']);
    $router->post('admin/announcements/update', [AdminController::class, 'updateAnnouncement']);
    $router->post('admin/announcements/action', [AdminController::class, 'processAnnouncement']);
    $router->post('admin/leave-requests/process', [AdminController::class, 'processLeaveRequest']);
    $router->post('admin/leave-types/save', [AdminController::class, 'saveLeaveType']);
    $router->post('admin/leave-types/toggle', [AdminController::class, 'toggleLeaveType']);
    $router->post('admin/leave-approval-settings/save', [AdminController::class, 'saveLeaveSettings']);
    $router->get('admin/pumps', [AdminController::class, 'pumps']);
    $router->get('admin/add-pump', [AdminController::class, 'addPump']);
    $router->get('admin/edit-pump', [AdminController::class, 'editPump']);
    $router->get('admin/pumps/export', [AdminController::class, 'exportPumps']);
    $router->post('admin/pumps/store', [AdminController::class, 'storePump']);
    $router->post('admin/pumps/update', [AdminController::class, 'updatePump']);
    $router->post('admin/pumps/delete', [AdminController::class, 'deletePump']);
    $router->post('admin/pumps/toggle', [AdminController::class, 'togglePump']);
    $router->get('admin/shift-management', [AdminController::class, 'shiftManagement']);
    $router->get('admin/add-shift', [AdminController::class, 'addShift']);
    $router->get('admin/edit-shift', [AdminController::class, 'editShift']);
    $router->post('admin/shifts/store', [AdminController::class, 'storeShift']);
    $router->post('admin/shifts/update', [AdminController::class, 'updateShift']);
    $router->post('admin/shifts/delete', [AdminController::class, 'deleteShift']);
    $router->post('admin/shifts/toggle', [AdminController::class, 'toggleShift']);
    $router->post('admin/duty-rosters/save', [AdminController::class, 'saveDutyRoster']);
    $router->post('admin/duty-rosters/publish', [AdminController::class, 'publishDutyRoster']);
    $router->post('admin/duty-rosters/archive', [AdminController::class, 'archiveDutyRoster']);
    $router->post('admin/duty-rosters/delete', [AdminController::class, 'deleteDutyRoster']);
    $router->post('admin/duty-assignments/save', [AdminController::class, 'saveDutyAssignment']);
    $router->post('admin/duty-assignments/cancel', [AdminController::class, 'cancelDutyAssignment']);
    $router->post('admin/duty-assignments/delete', [AdminController::class, 'deleteDutyAssignment']);
    $router->get('admin/activity-log', [AdminController::class, 'activityLog']);
    $router->get('admin/attendance-history/details', [AdminController::class, 'attendanceDetails']);
    $router->get('admin/attendance-history/selfie', [AdminController::class, 'attendanceSelfie']);
    $router->get(['admin', 'admin/dashboard'], [AdminController::class, 'dashboard']);
    $router->get(['', 'dashboard', 'attendance'], [AttendanceController::class, 'dashboard']);
    $router->get('attendance/clock-in', [AttendanceController::class, 'clockIn']);
    $router->post('attendance/clock-in', [AttendanceController::class, 'submitClockIn']);
    $router->post('attendance/clock-out', [AttendanceController::class, 'submitClockOut']);

    $router->get('attendance/clock-out', [AttendanceController::class, 'clockOut']);
    $router->get(['attendance/attendance_history', 'attendance/history'], [AttendanceController::class, 'attendanceHistoryPage']);
    $router->get('fuel-sales/history', [AttendanceController::class, 'fuelSalesHistory']);
    $router->get('duty-roster', [AttendanceController::class, 'dutyRoster']);
    $router->get(['supervisor/manage-duty-roster', 'manager/manage-duty-roster'], [SupervisorController::class, 'manageDutyRoster']);
    $router->get(['supervisor/fuel-sales', 'manager/fuel-sales'], [SupervisorController::class, 'fuelSales']);
    $router->get('leave-requests', [AttendanceController::class, 'leaveRequests']);
    $router->post('leave-requests', [AttendanceController::class, 'submitLeaveRequest']);
    $router->post('leave-requests/cancel', [AttendanceController::class, 'cancelLeaveRequest']);
    $router->get('profile', [AttendanceController::class, 'profile']);
    $router->get('profile/complete', [AttendanceController::class, 'completeProfile']);
    $router->post('profile/complete', [AttendanceController::class, 'storeCompletedProfile']);
    $router->get('profile/edit', [AttendanceController::class, 'editProfile']);
    $router->post('profile/edit', [AttendanceController::class, 'updateProfile']);
    $router->get('settings', [AttendanceController::class, 'settings']);
    $router->get('announcements', [AttendanceController::class, 'announcements']);
    $router->fallback([AttendanceController::class, 'notFound']);
};
