<?php

declare(strict_types=1);

return [
    'public_routes' => [
        'login',
        'auth/login',
        'logout',
        'auth/logout',
    ],

    'role_redirects' => [
        'Admin' => 'admin/dashboard',
        'Administrator' => 'admin/dashboard',
        'Manager' => 'admin/dashboard',
        'Supervisor' => 'admin/dashboard',
        'Accountant' => 'admin/dashboard',
        'Pump Attendant' => 'dashboard',
        'Cashier' => 'dashboard',
        'Security' => 'dashboard',
        'Driver' => 'dashboard',
    ],

    'permissions' => [
        'Admin' => ['*'],
        'Administrator' => ['*'],

        'Manager' => [
            'admin/dashboard',
            'admin/employees',
            'admin/edit-employee',
            'admin/employee-profile',
            'admin/employee-documents',
            'admin/employees/update',
            'admin/employees/upload-document',
            'admin/employees/delete-document',
            'admin/attendance-dashboard',
            'admin/attendance-history',
            'admin/fuel-sales',
            'admin/fuel-sales-dashboard',
            'admin/fuel-sales-history',
            'admin/verify-sales',
            'admin/fuel-sales/verify',
            'admin/fuel-sales-report',
            'admin/fuel-sales-reports',
            'admin/fuel-inventory',
            'admin/fuel-inventory/delivery',
            'admin/pumps',
            'admin/pumps/export',
            'admin/duty-roster',
            'admin/manage-duty-roster',
            'admin/calendar',
            'admin/duty-calendar',
            'admin/shift-management',
            'admin/pump-allocation',
            'admin/duty-rosters/*',
            'admin/duty-assignments/*',
            'admin/leave-dashboard',
            'admin/leave-requests',
            'admin/leave-requests/process',
            'admin/leave-history',
            'admin/announcements',
            'admin/announcement-details',
            'admin/reports-attendance',
            'admin/reports-fuel-sales',
            'admin/reports-employees',
            'admin/reports-duty-roster',
            'admin/reports-leave',
            'admin/reports-performance',
            'admin/profile',
            'admin/edit-profile',
            'admin/change-password',
            'dashboard',
            'attendance/*',
            'fuel-sales/*',
            'manager/fuel-sales',
            'duty-roster',
            'leave-requests',
            'profile',
            'profile/edit',
            'profile/change-password',
            'change-password',
            'settings',
        ],

        'Supervisor' => [
            'admin/dashboard',
            'admin/attendance-dashboard',
            'admin/attendance-history',
            'admin/attendance-settings',
            'admin/duty-roster',
            'admin/manage-duty-roster',
            'admin/calendar',
            'admin/duty-calendar',
            'admin/shift-management',
            'admin/add-shift',
            'admin/edit-shift',
            'admin/pump-allocation',
            'admin/shifts/*',
            'admin/duty-rosters/*',
            'admin/duty-assignments/*',
            'admin/leave-dashboard',
            'admin/leave-requests',
            'admin/leave-requests/process',
            'admin/leave-history',
            'admin/announcements',
            'admin/announcement-details',
            'admin/profile',
            'admin/edit-profile',
            'admin/change-password',
            'supervisor/manage-duty-roster',
        ],

        'Pump Attendant' => [
            'dashboard',
            'attendance/*',
            'fuel-sales/history',
            'duty-roster',
            'leave-requests',
            'profile',
            'leave-requests/*',
            'profile/edit',
            'profile/change-password',
            'change-password',
            'announcements',
            'settings',
        ],

        'Driver' => [
            'dashboard',
            'attendance/*',
            'leave-requests',
            'leave-requests/*',
            'profile',
            'profile/edit',
            'profile/change-password',
            'change-password',
            'announcements',
            'settings',
        ],

        'Cashier' => [
            'dashboard',
            'leave-requests/*',
            'attendance/*',
            'leave-requests',
            'profile',
            'announcements',
            'profile/edit',
            'profile/change-password',
            'change-password',
            'settings',
        ],

        'Security' => [
            'dashboard',
            'attendance/clock-in',
            'attendance/clock-out',
            'attendance/history',
            'attendance/attendance_history',
            'leave-requests',
            'leave-requests/*',
            'profile',
            'profile/edit',
            'profile/change-password',
            'announcements',
            'change-password',
            'settings',
        ],

        'Accountant' => [
            'admin',
            'admin/dashboard',
            'admin/attendance-dashboard',
            'admin/attendance-history',
            'admin/fuel-sales',
            'admin/fuel-sales-dashboard',
            'admin/fuel-sales-history',
            'admin/verify-sales',
            'admin/fuel-sales/verify',
            'admin/fuel-sales-report',
            'admin/fuel-sales-reports',
            'admin/pump-meter-history',
            'admin/duty-roster',
            'admin/manage-duty-roster',
            'admin/calendar',
            'admin/duty-calendar',
            'admin/shift-management',
            'admin/pump-allocation',
            'admin/leave-dashboard',
            'admin/leave-requests',
            'admin/leave-history',
            'admin/announcements',
            'admin/announcement-details',
            'admin/profile',
            'admin/edit-profile',
            'admin/change-password',
        ],
    ],
];



